[package]
name = "ff"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
chrono = "0.4.39"
crossterm = "0.28.1"
num_cpus = "1.16.0"
sysinfo = "0.33.1"
unicode-width = "0.2.0"
winreg = "0.55.0"
